import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import { AppWrapper } from "@/lib/ContextProvider";
import { Toaster } from "@/components/ui/toaster";
import TanstackProvider from "@/lib/TanstackProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackProvider>
        <AppWrapper>
          <body
            className={cn(
              "min-h-screen flex flex-col bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            {children}
            <Toaster />
          </body>
        </AppWrapper>
      </TanstackProvider>
    </html>
  );
}
