import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import LoadingBar from "@/components/loading-bar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function VerificationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex items-center justify-center flex-col bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LoadingBar>
          <main>{children}</main>
        </LoadingBar>
        <Toaster />
      </body>
    </html>
  );
}
