export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import { ToasterProvider } from "@/components/toaster-provider";
import LoadingBar from "@/components/loading-bar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={cn(
        "min-h-screen flex flex-col bg-background font-sans antialiased",
        fontSans.variable
      )}
    >
      <LoadingBar>
        <header>
          <Navigation />
        </header>
        <main>{children}</main>
        <footer className="bg-secondary w-full">
          <Footer />
        </footer>
        <ToasterProvider />
      </LoadingBar>
    </div>
  );
}
